name: Bug report
description: Report a bug or issue in WAL-G
title: "[BUG] "
labels: [bug]
body:
  - type: input
    id: db-name
    attributes:
      label: Database name
      description: WAL-G provides support for many databases. Please write the name of the database you use.
      placeholder: e.g. PostgreSQL, MongoDB
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Describe your problem
      description: Describe the issue you are facing
      placeholder: |
        // here is your problem
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Help us reproduce the issue
      placeholder: |
        1. Run command...
        2. See error...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Config and WAL-G logs
      description: Add config and WAL-G stdout/stderr logs for debugging. You can set WALG_LOG_LEVEL=DEVEL for more details.
      render: shell
      placeholder: |
        <details><summary>If you can, provide logs</summary>
        <p>

        ```bash
        any logs here
        ```

        </p>
        </details>
    validations:
      required: false