name: Build and Publish DEB Packages to GitHub Pages

on:
  push:
    tags:
      - 'v*'  # Запуск на новые версии (например, v3.0.2)

env:
  GO_VERSION: "1.22"

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64 ]
        os: [ ubuntu-22.04 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: sudo apt-get install -y devscripts debhelper dh-make dpkg-dev build-essential

      - name: Make deps
        run: make deps

      - name: Build WAL-G
        run: |
          make pg_build
          mv main/pg/wal-g wal-g-${{ matrix.arch }}

      - name: Debug WAL-G binary
        run: |
          ls -lh
          file wal-g-${{ matrix.arch }}

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create DEB package
        run: |
          mkdir -p wal-g-deb/DEBIAN
          mkdir -p wal-g-deb/usr/bin/
          cp wal-g-${{ matrix.arch }} wal-g-deb/usr/bin/wal-g
          chmod 755 wal-g-deb/usr/bin/wal-g
          cat <<EOF > wal-g-deb/DEBIAN/control
          Package: wal-g
          Version: ${VERSION}
          Section: utils
          Priority: optional
          Architecture: ${{ matrix.arch }}
          Maintainer: Your Name <your@email.com>
          Description: WAL-G backup tool for PostgreSQL
          EOF
          dpkg-deb --build wal-g-deb wal-g_${VERSION}_${{ matrix.arch }}.deb
      - name: Debug file location
        run: find . -name "wal-g_*.deb"

      - name: Debug DEB package
        run: |
          ls -lh
          ls -lh wal-g-deb
          dpkg --info wal-g_${VERSION}_${{ matrix.arch }}.deb || echo "DEB package not found"

      - name: Debug artifact path
        run: |
          echo "Checking for file: ./wal-g_${VERSION}_${{ matrix.arch }}.deb"
          ls -lh ./wal-g_${VERSION}_${{ matrix.arch }}.deb || echo "DEB package not found"
          
      - name: Upload DEB package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wal-g-deb-${{ matrix.arch }}
          path: wal-g_${env.VERSION}_${{ matrix.arch }}.deb